import type {
  Lead,
  Property,
  KanbanColumn,
  ChatMessage,
  User,
  Client,
  Plan,
  KpiData,
  ChartDataPoint,
} from './types'

// ---- Plans ----
export const plans: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 97,
    features: [
      'Ate 100 leads/mes',
      '1 numero WhatsApp',
      'Cadencia automatica basica',
      'Dashboard de metricas',
      'Suporte por email',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 197,
    isPopular: true,
    features: [
      'Ate 500 leads/mes',
      '3 numeros WhatsApp',
      'Cadencia avancada com IA',
      'Qualificacao automatica',
      'Integracao com portais',
      'Suporte prioritario',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 397,
    features: [
      'Leads ilimitados',
      'Numeros ilimitados',
      'IA personalizada',
      'API completa',
      'Gestor de conta dedicado',
      'SLA 99.9%',
      'Onboarding assistido',
    ],
  },
]

// ---- Leads ----
export const mockLeads: Lead[] = [
  {
    id: 'l1',
    name: 'Ana Carolina Silva',
    email: 'ana.silva@email.com',
    phone: '(11) 98765-4321',
    source: 'Portal ZAP',
    status: 'qualificacao',
    propertyId: 'p1',
    propertyTitle: 'Apartamento Jardins 120m2',
    createdAt: '2026-02-20',
    lastInteraction: '2026-02-24',
    notes: 'Interessada em visita no sabado',
    aiEnabled: true,
  },
  {
    id: 'l2',
    name: 'Ricardo Mendes',
    email: 'ricardo.m@email.com',
    phone: '(11) 97654-3210',
    source: 'Site proprio',
    status: 'qualificacao',
    propertyId: 'p2',
    propertyTitle: 'Casa Alphaville 350m2',
    createdAt: '2026-02-18',
    lastInteraction: '2026-02-23',
    aiEnabled: true,
  },
  {
    id: 'l3',
    name: 'Juliana Costa',
    email: 'ju.costa@email.com',
    phone: '(21) 99876-5432',
    source: 'Instagram',
    status: 'cadencia',
    propertyId: 'p3',
    propertyTitle: 'Cobertura Leblon 200m2',
    createdAt: '2026-02-15',
    lastInteraction: '2026-02-22',
    aiEnabled: true,
  },
  {
    id: 'l4',
    name: 'Pedro Oliveira',
    email: 'pedro.o@email.com',
    phone: '(11) 96543-2109',
    source: 'Indicacao',
    status: 'visita',
    propertyId: 'p1',
    propertyTitle: 'Apartamento Jardins 120m2',
    createdAt: '2026-02-10',
    lastInteraction: '2026-02-21',
    notes: 'Visitou e gostou muito. Vai fazer proposta.',
    aiEnabled: false,
  },
  {
    id: 'l5',
    name: 'Mariana Ferreira',
    email: 'mari.f@email.com',
    phone: '(31) 98432-1098',
    source: 'Portal OLX',
    status: 'proposta',
    propertyId: 'p4',
    propertyTitle: 'Sala Comercial Faria Lima',
    createdAt: '2026-02-05',
    lastInteraction: '2026-02-20',
    aiEnabled: true,
  },
  {
    id: 'l6',
    name: 'Lucas Andrade',
    email: 'lucas.a@email.com',
    phone: '(11) 95321-0987',
    source: 'Google Ads',
    status: 'contrato',
    propertyId: 'p2',
    propertyTitle: 'Casa Alphaville 350m2',
    createdAt: '2026-01-28',
    lastInteraction: '2026-02-19',
    aiEnabled: false,
  },
  {
    id: 'l7',
    name: 'Fernanda Lima',
    email: 'fer.lima@email.com',
    phone: '(21) 94210-9876',
    source: 'Portal ZAP',
    status: 'ganho',
    propertyId: 'p5',
    propertyTitle: 'Apartamento Barra 80m2',
    createdAt: '2026-01-20',
    lastInteraction: '2026-02-15',
    aiEnabled: false,
  },
  {
    id: 'l8',
    name: 'Bruno Santos',
    email: 'bruno.s@email.com',
    phone: '(11) 93109-8765',
    source: 'Site proprio',
    status: 'perda',
    propertyId: 'p1',
    propertyTitle: 'Apartamento Jardins 120m2',
    createdAt: '2026-01-15',
    lastInteraction: '2026-02-10',
    notes: 'Desistiu por questao de preco',
    aiEnabled: false,
  },
  {
    id: 'l9',
    name: 'Camila Rodrigues',
    email: 'camila.r@email.com',
    phone: '(11) 92098-7654',
    source: 'Instagram',
    status: 'qualificacao',
    propertyId: 'p3',
    propertyTitle: 'Cobertura Leblon 200m2',
    createdAt: '2026-02-23',
    lastInteraction: '2026-02-24',
    aiEnabled: true,
  },
  {
    id: 'l10',
    name: 'Thiago Barros',
    email: 'thiago.b@email.com',
    phone: '(41) 91987-6543',
    source: 'Indicacao',
    status: 'cadencia',
    propertyId: 'p6',
    propertyTitle: 'Terreno Granja Viana 500m2',
    createdAt: '2026-02-12',
    lastInteraction: '2026-02-22',
    aiEnabled: true,
  },
  {
    id: 'l11',
    name: 'Patricia Almeida',
    email: 'pat.alm@email.com',
    phone: '(11) 90876-5432',
    source: 'Google Ads',
    status: 'qualificacao',
    propertyId: 'p5',
    propertyTitle: 'Apartamento Barra 80m2',
    createdAt: '2026-02-19',
    lastInteraction: '2026-02-24',
    aiEnabled: true,
  },
  {
    id: 'l12',
    name: 'Rafael Moura',
    email: 'rafa.m@email.com',
    phone: '(21) 89765-4321',
    source: 'Portal ZAP',
    status: 'visita',
    propertyId: 'p4',
    propertyTitle: 'Sala Comercial Faria Lima',
    createdAt: '2026-02-08',
    lastInteraction: '2026-02-21',
    aiEnabled: true,
  },
]

// ---- Properties ----
export const mockProperties: Property[] = [
  {
    id: 'p1',
    title: 'Apartamento Jardins 120m2',
    type: 'apartamento',
    description:
      'Lindo apartamento reformado no coracao dos Jardins. 3 suites, varanda gourmet, 2 vagas de garagem. Lazer completo no condominio.',
    address: 'Rua Oscar Freire, 1200',
    city: 'Sao Paulo',
    state: 'SP',
    neighborhood: 'Jardins',
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    parkingType: 'coberta',
    bbqType: 'carvao',
    area: 120,
    privateArea: 105,
    salePrice: 1850000,
    isMultiUnit: false,
    financialNotes: 'Aceita financiamento bancario. FGTS permitido.',
    paymentOptions: 'Entrada + financiamento ou a vista com desconto de 5%',
    status: 'ativo',
    images: [
      {
        id: 'img1',
        url: '/placeholder.svg',
        description: 'Sala de estar ampla',
      },
      { id: 'img2', url: '/placeholder.svg', description: 'Cozinha gourmet' },
      { id: 'img3', url: '/placeholder.svg', description: 'Suite master' },
    ],
    announcements: [
      {
        id: 'a1',
        portal: 'ZAP Imoveis',
        url: 'https://zap.com.br',
        status: 'ativo',
        publishedAt: '2026-02-01',
      },
      {
        id: 'a2',
        portal: 'Viva Real',
        url: 'https://vivareal.com.br',
        status: 'ativo',
        publishedAt: '2026-02-01',
      },
    ],
    adLinks: [
      {
        id: 'ad1',
        platform: 'facebook',
        campaignName: 'Jardins Premium - Fev 2026',
        url: 'https://facebook.com/ads/123',
      },
      {
        id: 'ad2',
        platform: 'instagram',
        campaignName: 'Jardins Reels',
        url: 'https://instagram.com/ads/456',
      },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'p2',
    title: 'Casa Alphaville 350m2',
    type: 'casa',
    description:
      'Casa em condominio fechado com 4 suites, piscina, churrasqueira e campo de futebol. Seguranca 24h.',
    address: 'Alameda das Palmeiras, 500',
    city: 'Barueri',
    state: 'SP',
    neighborhood: 'Alphaville',
    bedrooms: 4,
    bathrooms: 5,
    parkingSpaces: 4,
    parkingType: 'coberta',
    bbqType: 'carvao',
    area: 350,
    privateArea: 280,
    salePrice: 3200000,
    isMultiUnit: false,
    financialNotes: 'Aceita permuta parcial por apartamento.',
    paymentOptions: 'Entrada de 30% + saldo financiado em 120x',
    status: 'ativo',
    images: [
      { id: 'img4', url: '/placeholder.svg', description: 'Fachada da casa' },
      {
        id: 'img5',
        url: '/placeholder.svg',
        description: 'Piscina e area de lazer',
      },
    ],
    announcements: [
      {
        id: 'a3',
        portal: 'ZAP Imoveis',
        url: 'https://zap.com.br',
        status: 'ativo',
        publishedAt: '2026-01-20',
      },
    ],
    adLinks: [],
    createdAt: '2026-01-10',
  },
  {
    id: 'p3',
    title: 'Cobertura Leblon 200m2',
    type: 'cobertura',
    description:
      'Cobertura duplex com vista para o mar. 3 suites, terraco panoramico, jacuzzi. A 2 quadras da praia.',
    address: 'Av. Delfim Moreira, 800',
    city: 'Rio de Janeiro',
    state: 'RJ',
    neighborhood: 'Leblon',
    bedrooms: 3,
    bathrooms: 4,
    parkingSpaces: 3,
    parkingType: 'coberta',
    bbqType: 'eletrica',
    area: 200,
    privateArea: 180,
    salePrice: 5500000,
    isMultiUnit: false,
    status: 'ativo',
    images: [
      { id: 'img6', url: '/placeholder.svg', description: 'Vista do terraco' },
    ],
    announcements: [],
    adLinks: [
      {
        id: 'ad3',
        platform: 'tiktok',
        campaignName: 'Leblon Luxo',
        url: 'https://tiktok.com/ads/789',
      },
    ],
    createdAt: '2026-02-01',
  },
  {
    id: 'p4',
    title: 'Sala Comercial Faria Lima',
    type: 'comercial',
    description:
      'Conjunto comercial com 80m2, ar condicionado central, piso elevado, infraestrutura completa para escritorio.',
    address: 'Av. Faria Lima, 3500',
    city: 'Sao Paulo',
    state: 'SP',
    neighborhood: 'Itaim Bibi',
    bedrooms: 0,
    bathrooms: 2,
    parkingSpaces: 2,
    parkingType: 'coberta',
    bbqType: 'nenhuma',
    area: 80,
    privateArea: 72,
    rentPrice: 8500,
    isMultiUnit: false,
    status: 'ativo',
    images: [],
    announcements: [
      {
        id: 'a4',
        portal: 'OLX',
        url: 'https://olx.com.br',
        status: 'ativo',
        publishedAt: '2026-02-10',
      },
    ],
    adLinks: [],
    createdAt: '2026-01-25',
  },
  {
    id: 'p5',
    title: 'Apartamento Barra 80m2',
    type: 'apartamento',
    description:
      'Apartamento 2 quartos com suite, varanda, lazer completo. Proximo ao metro e shopping.',
    address: 'Av. das Americas, 4200',
    city: 'Rio de Janeiro',
    state: 'RJ',
    neighborhood: 'Barra da Tijuca',
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    parkingType: 'descoberta',
    bbqType: 'nenhuma',
    area: 80,
    privateArea: 65,
    salePrice: 650000,
    isMultiUnit: false,
    status: 'vendido',
    images: [
      { id: 'img7', url: '/placeholder.svg', description: 'Sala e varanda' },
      {
        id: 'img8',
        url: '/placeholder.svg',
        description: 'Vista do condominio',
      },
    ],
    announcements: [],
    adLinks: [],
    createdAt: '2025-12-01',
  },
  {
    id: 'p6',
    title: 'Terreno Granja Viana 500m2',
    type: 'terreno',
    description:
      'Terreno plano em condominio fechado com infraestrutura completa. Otima topografia para construcao.',
    address: 'Rua dos Ipes, 100',
    city: 'Cotia',
    state: 'SP',
    neighborhood: 'Granja Viana',
    bedrooms: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    parkingType: 'descoberta',
    bbqType: 'nenhuma',
    area: 500,
    salePrice: 450000,
    isMultiUnit: false,
    status: 'ativo',
    images: [],
    announcements: [],
    adLinks: [],
    createdAt: '2026-02-05',
  },
  {
    id: 'p7',
    title: 'Residencial Flores do Campo',
    type: 'apartamento',
    description:
      'Empreendimento com 48 unidades, apartamentos de 2 e 3 dormitorios. Lazer completo, proximo ao metro.',
    address: 'Rua das Flores, 300',
    city: 'Sao Paulo',
    state: 'SP',
    neighborhood: 'Vila Mariana',
    bedrooms: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    parkingType: 'coberta',
    bbqType: 'carvao',
    area: 0,
    isMultiUnit: true,
    units: [
      {
        id: 'u1',
        name: 'Unid 101',
        bedrooms: 2,
        parkingSpaces: 1,
        privateArea: 55,
        parkingArea: 12,
        totalArea: 67,
        downPayment: 48000,
        annualBonus: 12000,
        installmentValue: 1800,
        status: 'disponivel',
      },
      {
        id: 'u2',
        name: 'Unid 102',
        bedrooms: 2,
        parkingSpaces: 1,
        privateArea: 55,
        parkingArea: 12,
        totalArea: 67,
        downPayment: 48000,
        annualBonus: 12000,
        installmentValue: 1800,
        status: 'reservado',
      },
      {
        id: 'u3',
        name: 'Unid 201',
        bedrooms: 3,
        parkingSpaces: 2,
        privateArea: 72,
        parkingArea: 24,
        totalArea: 96,
        downPayment: 62000,
        annualBonus: 15000,
        installmentValue: 2400,
        status: 'disponivel',
      },
      {
        id: 'u4',
        name: 'Unid 202',
        bedrooms: 3,
        parkingSpaces: 2,
        privateArea: 72,
        parkingArea: 24,
        totalArea: 96,
        downPayment: 62000,
        annualBonus: 15000,
        installmentValue: 2400,
        status: 'vendido',
      },
      {
        id: 'u5',
        name: 'Unid 301',
        bedrooms: 2,
        parkingSpaces: 1,
        privateArea: 55,
        parkingArea: 12,
        totalArea: 67,
        downPayment: 49500,
        annualBonus: 12000,
        installmentValue: 1850,
        status: 'disponivel',
      },
    ],
    financialNotes:
      'Aceita financiamento Caixa e Banco do Brasil. Programa MCMV disponivel para unidades de 2 dorms.',
    paymentOptions:
      'Entrada parcelada em ate 36x, saldo financiado em 420 meses',
    status: 'ativo',
    images: [
      {
        id: 'img9',
        url: '/placeholder.svg',
        description: 'Fachada do empreendimento',
      },
    ],
    announcements: [
      {
        id: 'a5',
        portal: 'ZAP Imoveis',
        url: 'https://zap.com.br',
        status: 'ativo',
        publishedAt: '2026-02-15',
      },
    ],
    adLinks: [
      {
        id: 'ad4',
        platform: 'facebook',
        campaignName: 'Flores do Campo - Lancamento',
        url: 'https://facebook.com/ads/abc',
      },
      {
        id: 'ad5',
        platform: 'instagram',
        campaignName: 'Flores do Campo Reels',
        url: 'https://instagram.com/ads/def',
      },
    ],
    createdAt: '2026-02-10',
  },
]

// ---- Kanban Columns ----
export const mockKanbanColumns: KanbanColumn[] = [
  {
    id: 'qualificacao',
    title: 'Qualificacao',
    color: 'bg-[#6366f1]',
    cards: mockLeads.filter(l => l.status === 'qualificacao'),
  },
  {
    id: 'cadencia',
    title: 'Cadencia & Alimentacao',
    color: 'bg-[#f59e0b]',
    cards: mockLeads.filter(l => l.status === 'cadencia'),
  },
  {
    id: 'visita',
    title: 'Visita',
    color: 'bg-[#06b6d4]',
    cards: mockLeads.filter(l => l.status === 'visita'),
  },
  {
    id: 'proposta',
    title: 'Proposta',
    color: 'bg-[#10b981]',
    cards: mockLeads.filter(l => l.status === 'proposta'),
  },
  {
    id: 'contrato',
    title: 'Contrato',
    color: 'bg-[#8b5cf6]',
    cards: mockLeads.filter(l => l.status === 'contrato'),
  },
  {
    id: 'resultado',
    title: 'Ganho / Perda',
    color: 'bg-[#737373]',
    cards: mockLeads.filter(l => l.status === 'ganho' || l.status === 'perda'),
  },
]

// ---- Chat Messages ----
export const mockChatMessages: ChatMessage[] = [
  {
    id: 'c1',
    sender: 'lead',
    content: 'Ola, vi o anuncio do apartamento nos Jardins e tenho interesse.',
    timestamp: '2026-02-24 09:00',
  },
  {
    id: 'c2',
    sender: 'ai',
    content:
      'Ola Ana! Que bom saber do seu interesse. O apartamento tem 120m2, 3 suites e fica na Oscar Freire. Gostaria de agendar uma visita?',
    timestamp: '2026-02-24 09:01',
  },
  {
    id: 'c3',
    sender: 'lead',
    content: 'Sim! Pode ser sabado de manha?',
    timestamp: '2026-02-24 09:05',
  },
  {
    id: 'c4',
    sender: 'ai',
    content: 'Perfeito! Tenho horario as 10h ou 11h no sabado. Qual prefere?',
    timestamp: '2026-02-24 09:06',
  },
  {
    id: 'c5',
    sender: 'lead',
    content: '10h esta otimo!',
    timestamp: '2026-02-24 09:10',
  },
  {
    id: 'c6',
    sender: 'agent',
    content:
      'Ana, confirmo sua visita para sabado as 10h. Vou te enviar o endereco completo por WhatsApp. Ate la!',
    timestamp: '2026-02-24 09:15',
  },
]

// ---- Client Dashboard KPIs ----
export const clientKpis: KpiData[] = [
  {
    label: 'Negociacao Ativa',
    value: 8,
    change: 12,
    changeLabel: 'vs mes anterior',
  },
  {
    label: 'Cadencia / Follow-up',
    value: 4,
    change: -3,
    changeLabel: 'vs mes anterior',
  },
]

// ---- Client Chart Data ----
export const clientChartData: ChartDataPoint[] = [
  { month: 'Set', leads: 18, fechados: 3 },
  { month: 'Out', leads: 22, fechados: 4 },
  { month: 'Nov', leads: 28, fechados: 5 },
  { month: 'Dez', leads: 15, fechados: 2 },
  { month: 'Jan', leads: 32, fechados: 6 },
  { month: 'Fev', leads: 24, fechados: 4 },
]

// ---- Admin KPIs ----
export const adminKpis: KpiData[] = [
  {
    label: 'Clientes Ativos',
    value: 142,
    change: 8,
    changeLabel: 'vs mes anterior',
  },
  {
    label: 'Churn Rate',
    value: '3.2%',
    change: -0.5,
    changeLabel: 'vs mes anterior',
  },
  {
    label: 'Em Trial',
    value: 23,
    change: 12,
    changeLabel: 'novos esta semana',
  },
  {
    label: 'MRR',
    value: 'R$ 28.4k',
    change: 15,
    changeLabel: 'vs mes anterior',
  },
]

// ---- Admin Chart Data ----
export const adminChartData: ChartDataPoint[] = [
  { month: 'Set', leads: 12, fechados: 2, faturamento: 22400 },
  { month: 'Out', leads: 18, fechados: 3, faturamento: 24100 },
  { month: 'Nov', leads: 15, fechados: 4, faturamento: 25800 },
  { month: 'Dez', leads: 20, fechados: 5, faturamento: 26500 },
  { month: 'Jan', leads: 25, fechados: 3, faturamento: 27900 },
  { month: 'Fev', leads: 22, fechados: 6, faturamento: 28400 },
]

// ---- Users ----
export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Carlos Henrique',
    email: 'carlos@valya.app',
    phone: '(11) 99999-0001',
    role: 'admin',
    isActive: true,
    createdAt: '2025-06-01',
  },
  {
    id: 'u2',
    name: 'Maria Souza',
    email: 'maria.s@email.com',
    phone: '(11) 99999-0002',
    role: 'client',
    creci: '123456-F',
    agency: 'Imobiliaria Souza',
    isActive: true,
    createdAt: '2025-08-15',
  },
  {
    id: 'u3',
    name: 'Jose Pereira',
    email: 'jose.p@email.com',
    phone: '(21) 99999-0003',
    role: 'client',
    creci: '789012-F',
    agency: 'JP Imoveis',
    isActive: true,
    createdAt: '2025-09-20',
  },
  {
    id: 'u4',
    name: 'Ana Beatriz',
    email: 'ana.b@email.com',
    phone: '(31) 99999-0004',
    role: 'client',
    creci: '345678-F',
    agency: 'AB Corretora',
    isActive: false,
    createdAt: '2025-10-10',
  },
  {
    id: 'u5',
    name: 'Roberto Dias',
    email: 'roberto.d@email.com',
    phone: '(41) 99999-0005',
    role: 'client',
    creci: '901234-F',
    agency: 'Dias Imoveis',
    isActive: true,
    createdAt: '2025-11-01',
  },
  {
    id: 'u6',
    name: 'Leticia Alves',
    email: 'leticia@valya.app',
    phone: '(11) 99999-0006',
    role: 'admin',
    isActive: true,
    createdAt: '2025-07-01',
  },
]

// ---- Clients (Admin view) ----
export const mockClients: Client[] = [
  {
    id: 'cl1',
    name: 'Maria Souza',
    email: 'maria.s@email.com',
    phone: '(11) 99999-0002',
    creci: '123456-F',
    agency: 'Imobiliaria Souza',
    plan: plans[1],
    subscriptionStatus: 'ativo',
    daysToExpire: 22,
    hasCard: true,
    leadsCount: 45,
    propertiesCount: 12,
    createdAt: '2025-08-15',
    payments: [
      {
        id: 'pay1',
        date: '2026-02-01',
        amount: 197,
        status: 'pago',
        method: 'Cartao',
      },
      {
        id: 'pay2',
        date: '2026-01-01',
        amount: 197,
        status: 'pago',
        method: 'Cartao',
      },
      {
        id: 'pay3',
        date: '2025-12-01',
        amount: 197,
        status: 'pago',
        method: 'Cartao',
      },
    ],
  },
  {
    id: 'cl2',
    name: 'Jose Pereira',
    email: 'jose.p@email.com',
    phone: '(21) 99999-0003',
    creci: '789012-F',
    agency: 'JP Imoveis',
    plan: plans[0],
    subscriptionStatus: 'trial',
    daysToExpire: 5,
    hasCard: false,
    leadsCount: 8,
    propertiesCount: 3,
    createdAt: '2025-09-20',
    payments: [],
  },
  {
    id: 'cl3',
    name: 'Ana Beatriz',
    email: 'ana.b@email.com',
    phone: '(31) 99999-0004',
    creci: '345678-F',
    agency: 'AB Corretora',
    plan: plans[2],
    subscriptionStatus: 'expirado',
    daysToExpire: 0,
    hasCard: true,
    leadsCount: 120,
    propertiesCount: 28,
    createdAt: '2025-10-10',
    payments: [
      {
        id: 'pay4',
        date: '2026-01-01',
        amount: 397,
        status: 'falhou',
        method: 'Cartao',
      },
      {
        id: 'pay5',
        date: '2025-12-01',
        amount: 397,
        status: 'pago',
        method: 'Cartao',
      },
    ],
  },
  {
    id: 'cl4',
    name: 'Roberto Dias',
    email: 'roberto.d@email.com',
    phone: '(41) 99999-0005',
    creci: '901234-F',
    agency: 'Dias Imoveis',
    plan: plans[1],
    subscriptionStatus: 'ativo',
    daysToExpire: 18,
    hasCard: true,
    leadsCount: 67,
    propertiesCount: 15,
    createdAt: '2025-11-01',
    payments: [
      {
        id: 'pay6',
        date: '2026-02-01',
        amount: 197,
        status: 'pago',
        method: 'Boleto',
      },
      {
        id: 'pay7',
        date: '2026-01-01',
        amount: 197,
        status: 'pago',
        method: 'Boleto',
      },
    ],
  },
  {
    id: 'cl5',
    name: 'Fernanda Torres',
    email: 'fer.torres@email.com',
    phone: '(51) 99999-0007',
    creci: '567890-F',
    agency: 'Torres Imoveis',
    plan: plans[0],
    subscriptionStatus: 'ativo',
    daysToExpire: 30,
    hasCard: true,
    leadsCount: 22,
    propertiesCount: 6,
    createdAt: '2026-01-05',
    payments: [
      {
        id: 'pay8',
        date: '2026-02-01',
        amount: 97,
        status: 'pago',
        method: 'PIX',
      },
    ],
  },
]

// ---- Mock current user for client panel ----
export const currentUser: User = {
  id: 'u2',
  name: 'Maria Souza',
  email: 'maria.s@email.com',
  phone: '(11) 99999-0002',
  role: 'client',
  creci: '123456-F',
  agency: 'Imobiliaria Souza',
  bio: 'Corretora de imoveis ha 8 anos, especializada em imoveis de alto padrao na regiao dos Jardins.',
  isActive: true,
  createdAt: '2025-08-15',
}

// ---- Subscription state mock ----
export const mockSubscription = {
  daysToExpire: 7,
  hasCard: false,
  status: 'ativo' as const,
}

// ---- Helper to format currency ----
export function formatCurrency(value: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}
